name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    
    name: Lint check and Testing
    
    runs-on: macos-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
    
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run android Linter
        run: ./gradlew/lintDebug
        
      - name: Unit tests
        run: ./gradlew testDebug
        
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
